### ISSUE TITLE
Failed migration

### ISSUE THREAD

**Issue by Carreau** [minrk/migrate-issues#4]
Not sure why, seem to get the wrong issue number:

I'm using the patch version of my other PR.

```
$ migrate-issues ipython/ipython jupyter/nbconvert 9068
Migrating ipython/ipython#9068 to jupyter/nbconvert
Using listings instead of verbatim to enable code wrap
Migrating 3 comments
Waiting for repos/jupyter/nbconvert/import/issues/401760
/usr/local/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:
// 16:in `on_complete': GET https://api.github.com/repos/jupyter/nbconvert/import/issues/401760: 404 - Not Found \n
// See: https://developer.github.com/v3 (Octokit::NotFound)
    from /usr/local/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    from /usr/local/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /usr/local/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /usr/local/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /usr/local/lib/ruby/gems/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
    from /usr/local/lib/ruby/gems/2.2.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/connection.rb:154:in `request'
    from /usr/local/lib/ruby/gems/2.2.0/gems/octokit-4.2.0/lib/octokit/connection.rb:19:in `get'
    from /Users/bussonniermatthias/bin/migrate-issues:148:in `wait_for_import'
    from /Users/bussonniermatthias/bin/migrate-issues:197:in `block in <main>'
    from /Users/bussonniermatthias/bin/migrate-issues:192:in `map'
    from /Users/bussonniermatthias/bin/migrate-issues:192:in `<main>'
```

**Comment by minrk** [comment]
Where do you get the indication that the issue number is wrong? The number on `/import/issues/N` is the _import id_, not the issue number.

**Comment by Carreau** [comment]
> Where do you get the indication that the issue number is wrong? The number on /import/issues/N is the import id, not the issue number.

Ah, yes, my bad, I was in  a hurry to go in a meeting.

**Comment by Carreau** [comment]
here is another error message I get whem trying to migrate for another issue. 

```
$ migrate-issues ipython/ipython jupyter/notebook 9067
Migrating ipython/ipython#9067 to jupyter/notebook
Error message is not completely visible within the browser screen
Migrating 3 comments
Waiting for repos/jupyter/notebook/import/issues/402808
#<Sawyer::Resource:0x007fb6aad043d8>
Failed to migrate ipython/ipython/9067
```

**Comment by minrk** [comment]
I wonder if it's the 2fa confusing things.

**Comment by Carreau** [comment]
> I wonder if it's the 2fa confusing things.

I wonder why it would as others migration do work. And IIUC the 2fa is just there to get a token that get reused, and is never asked again. 

```
$ cat ~/.netrc
machine api.github.com
  login carreau
  password 0a1b2c3d4e5f67
```

**Comment by Carreau** [comment]
Aha:

```
migrate-issues ipython/ipython jupyter/notebook 8996
Migrating ipython/ipython#8996 to jupyter/notebook
Nested SVG elements unsupported
Migrating 6 comments
Waiting for repos/jupyter/notebook/import/issues/403023
#<Sawyer::Resource:0x007fe59bae38e0>
#<Sawyer::Resource:0x007fe59bae2710>
#<Sawyer::Resource:0x007fe59bae16f8>
Failed to migrate ipython/ipython/8996
```

Has 3 times the `#<Sawyer>` thing... and the issue has.... 3 images !

**Comment by minrk** [comment]
Aha, maybe migration doesn't work with images? That would be...interesting.
